### ISSUE TITLE
trainer appaers Unknown label type:array([0L,0L,......1L,0L,1L],dtype=object)

### ISSUE THREAD

**Issue by chenlihuang** [phunterlau/dga_classifier#2]
now l failed to reappeare  the error because of the MemoryError in  XX,yy = X[p],Y[p]
but the screenshot can show :line 42
    probas_ = classifier.fit(XX[:cut_off], yy[:cut_off]).predict(XX[cut_off:])
ValueError : Unknown label type:array([0L,0L,......1L,0L,1L],dtype=object)

in my view ,problem in the data type ,but l can't find the cirtical,so l need your help

**Comment by chenlihuang** [comment]
@phunterlau

**Comment by chenlihuang** [comment]
l reset computer then reappeare the error like following:
Traceback (most recent call last):
  File "E:/�о����׶�/DGAʶ��/�޸�/trainer.py", line 42, in <module>
    probas_ = classifier.fit(XX[:cut_off], yy[:cut_off]).predict(XX[cut_off:])
  File "C:\Python27\lib\site-packages\sklearn\svm\base.py", line 151, in fit
    y = self._validate_targets(y)
  File "C:\Python27\lib\site-packages\sklearn\svm\base.py", line 515, in _validate_targets
    check_classification_targets(y)
  File "C:\Python27\lib\site-packages\sklearn\utils\multiclass.py", line 173, in check_classification_targets
    raise ValueError("Unknown label type: %r" % y)
ValueError: Unknown label type: array([0L, 0L, 0L, ..., 1L, 0L, 0L], dtype=object)

**Comment by phunterlau** [comment]
can you post your script for reproducing this error?

**Comment by chenlihuang** [comment]
what script do you mean?
